# 이 워크플로우는 update.py 파일을 실행합니다. 즉 README.md 파일을 업데이트합니다.

name: Update readme # GitHub Actions 탭에서 확인할 수 있는 액션 이름

on: # jobs가 실행되어야 하는 상황 정의
  push:
    branches: [main] # main 브랜치에 push가 발생했을 때
  pull_request:

jobs: # 실제 실행될 내용
  build:
    runs-on: ubuntu-latest # 빌드 환경
    steps:
    - uses: actions/checkout@v3 # checkout
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Run update.jar
      run: java -jar update.jar
      
    - name: Commit changes # 3) 추가된 파일 commit
      run: |
        git config --global user.name 'hazzokko' # 유저명
        git config --global user.email 'hazzokko@gmail.com' # 유저 이메일
        git add -A
        git commit -am "auto update README.md" # 커밋 메시지
    - name: Push changes # 4) 메인에 푸시
      run: |
        git push
